using Moq;
using System;
using System.Linq;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace ProgramNamespace.Tests
{
	[TestClass]
	public class ProgramClassTests
	{
		private ProgramClass _programClassTests;
		private Mock<IDependency> _dependency1;
		private Mock<IDependency> _dependency2;

		[TestInitialize]
		public void SetUp()
		{
			_dependency1 = new Mock<IDependency>();
			_dependency2 = new Mock<IDependency>();
			_programClassTests = new ProgramClass(_dependency1.Object, _dependency2.Object);
		}

		[TestMethod]
		public void DoUsefulWorkTest()
		{
			int work_t = 0;
			int work2_t = 0;	
			int actual = _programClassTests.DoUsefulWork();
			int expected = 0;
			Assert.AreEqual(expected, actual);
			Assert.Fail("autogenerated");
		}
	}
}