set_property IOSTANDARD LVCMOS18 [get_ports {Pout[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Pout[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Pout[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Pout[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Pout[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports RST]
set_property IOSTANDARD LVCMOS18 [get_ports CLK]
set_property PACKAGE_PIN P2 [get_ports {Pout[0]}]
set_property PACKAGE_PIN R2 [get_ports {Pout[1]}]
set_property PACKAGE_PIN U1 [get_ports {Pout[2]}]
set_property PACKAGE_PIN P5 [get_ports {Pout[3]}]
set_property PACKAGE_PIN R1 [get_ports {Pout[4]}]
set_property PACKAGE_PIN P4 [get_ports RST]


set_property IOSTANDARD LVCMOS18 [get_ports RST_0]
set_property IOSTANDARD LVCMOS18 [get_ports {Pout_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Pout_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Pout_0[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Pout_0[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Pout_0[4]}]
set_property PACKAGE_PIN P4 [get_ports RST_0]
set_property PACKAGE_PIN P2 [get_ports {Pout_0[0]}]
set_property PACKAGE_PIN R2 [get_ports {Pout_0[1]}]
set_property PACKAGE_PIN U1 [get_ports {Pout_0[2]}]
set_property PACKAGE_PIN P5 [get_ports {Pout_0[3]}]
set_property PACKAGE_PIN R1 [get_ports {Pout_0[4]}]
