set_property PACKAGE_PIN P4 [get_ports in1]
set_property PACKAGE_PIN P3 [get_ports in2]
set_property PACKAGE_PIN R3 [get_ports in3]
set_property PACKAGE_PIN P2 [get_ports Q]
set_property IOSTANDARD LVCMOS18 [get_ports in1]
set_property IOSTANDARD LVCMOS18 [get_ports in2]
set_property IOSTANDARD LVCMOS18 [get_ports in3]
set_property IOSTANDARD LVCMOS18 [get_ports Q]
